CREATE TABLE IF NOT EXISTS "cv_parsed_data" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL UNIQUE,
	"status" text DEFAULT 'pending' NOT NULL,
	"error_message" text,
	"extracted_full_name" text,
	"extracted_title" text,
	"extracted_skills" text[],
	"extracted_bio" text,
	"extracted_location" text,
	"extracted_country" text,
	"extracted_experience_years" integer,
	"extracted_education" text,
	"extracted_work_history" text,
	"extracted_certifications" text[],
	"section_data" text,
	"confidence_data" text,
	"cv_file_url" text,
	"parsed_at" timestamp with time zone,
	"confirmed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "cv_parsed_data_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE
);
