import { storage } from "../../storage";

export async function seedProductionJobs(): Promise<void> {
  try {
    const existingJobs = await storage.getAllJobs();
    if (existingJobs.length > 0) {
      console.log("ℹ️ Jobs already exist, skipping seed");
      return;
    }

    const adminUser = await storage.getUserByEmail("lorisbarbisan@gmail.com");
    if (!adminUser) {
      console.log("⚠️ Admin user not found, skipping job seed");
      return;
    }

    const recruiterId = adminUser.id;

    const jobs = [
      {
        recruiter_id: recruiterId,
        title: "Stage Manager",
        company: "Apex Events Group",
        location: "London, UK",
        type: "published",
        rate: "£350/day",
        description: "We are looking for an experienced Stage Manager to oversee all backstage operations for a large-scale music festival. You will coordinate artist arrivals, manage stage changeovers, and ensure the event runs on schedule. Must have excellent communication skills and experience with live music events.",
        status: "active",
        event_date: "2026-03-15",
        end_date: "2026-03-17",
        start_time: "08:00",
        end_time: "23:00",
        duration_type: "multi-day",
        days: 3,
        contract_type: "freelance",
      },
      {
        recruiter_id: recruiterId,
        title: "Event Photographer",
        company: "Apex Events Group",
        location: "Manchester, UK",
        type: "published",
        rate: "£250/day",
        description: "Seeking a professional event photographer to capture candid and posed shots at a major corporate awards ceremony. You will deliver edited high-resolution images within 48 hours. Portfolio showcasing event photography experience required.",
        status: "active",
        event_date: "2026-04-10",
        start_time: "17:00",
        end_time: "23:30",
        duration_type: "single-day",
        days: 1,
        contract_type: "freelance",
      },
      {
        recruiter_id: recruiterId,
        title: "Sound Engineer",
        company: "LiveWire Productions",
        location: "Birmingham, UK",
        type: "published",
        rate: "£400/day",
        description: "Experienced sound engineer needed for a 3-day outdoor festival. Responsibilities include system setup, live mixing for multiple stages, and troubleshooting. Must be proficient with digital mixing consoles and have experience with large PA systems.",
        status: "active",
        event_date: "2026-05-20",
        end_date: "2026-05-22",
        start_time: "07:00",
        end_time: "00:00",
        duration_type: "multi-day",
        days: 3,
        contract_type: "freelance",
      },
      {
        recruiter_id: recruiterId,
        title: "Wedding Coordinator",
        company: "Blossom Weddings",
        location: "Edinburgh, UK",
        type: "published",
        rate: "£300/day",
        description: "Blossom Weddings is hiring a day-of wedding coordinator for a luxury countryside wedding. You will manage vendor arrivals, coordinate the timeline, handle guest queries, and ensure the couple has a stress-free day. Previous wedding coordination experience essential.",
        status: "active",
        event_date: "2026-06-14",
        start_time: "09:00",
        end_time: "22:00",
        duration_type: "single-day",
        days: 1,
        contract_type: "freelance",
      },
      {
        recruiter_id: recruiterId,
        title: "Lighting Technician",
        company: "LiveWire Productions",
        location: "London, UK",
        type: "published",
        rate: "£320/day",
        description: "We need a skilled lighting technician for a West End theatre production transfer. Duties include rig setup, programming, and operating lighting cues during performances. Experience with ETC and MA Lighting consoles preferred.",
        status: "active",
        event_date: "2026-04-01",
        end_date: "2026-04-30",
        start_time: "14:00",
        end_time: "23:00",
        duration_type: "multi-day",
        days: 30,
        contract_type: "freelance",
      },
      {
        recruiter_id: recruiterId,
        title: "Catering Manager",
        company: "Silver Spoon Catering",
        location: "Bristol, UK",
        type: "published",
        rate: "£280/day",
        description: "Silver Spoon Catering requires a catering manager for a 500-guest charity gala dinner. You will oversee kitchen coordination, service staff, and ensure dietary requirements are met. Food hygiene certification and large event catering experience required.",
        status: "active",
        event_date: "2026-03-28",
        start_time: "12:00",
        end_time: "23:00",
        duration_type: "single-day",
        days: 1,
        contract_type: "freelance",
      },
      {
        recruiter_id: recruiterId,
        title: "AV Technician",
        company: "TechStage Solutions",
        location: "Leeds, UK",
        type: "published",
        rate: "£300/day",
        description: "AV Technician needed for a 2-day tech conference. Responsibilities include setting up projectors, screens, microphones, and live streaming equipment. Must be comfortable troubleshooting under pressure and have experience with hybrid events.",
        status: "active",
        event_date: "2026-05-05",
        end_date: "2026-05-06",
        start_time: "07:00",
        end_time: "19:00",
        duration_type: "multi-day",
        days: 2,
        contract_type: "freelance",
      },
      {
        recruiter_id: recruiterId,
        title: "Event Host / MC",
        company: "Apex Events Group",
        location: "Glasgow, UK",
        type: "published",
        rate: "£500/event",
        description: "Charismatic and professional event host needed for a corporate product launch. You will introduce speakers, manage audience engagement, and keep the event flowing smoothly. Public speaking experience and confident stage presence essential.",
        status: "active",
        event_date: "2026-04-22",
        start_time: "18:00",
        end_time: "22:00",
        duration_type: "single-day",
        days: 1,
        contract_type: "freelance",
      },
      {
        recruiter_id: recruiterId,
        title: "Security Team Lead",
        company: "Guardian Event Security",
        location: "London, UK",
        type: "private",
        rate: "£280/day",
        description: "Security team lead required for a high-profile private event. You will manage a team of 15 security personnel, coordinate access control, and liaise with venue management. SIA licence and event security management experience mandatory.",
        status: "active",
        event_date: "2026-04-18",
        start_time: "10:00",
        end_time: "02:00",
        duration_type: "single-day",
        days: 1,
        contract_type: "freelance",
      },
      {
        recruiter_id: recruiterId,
        title: "Festival Bar Staff",
        company: "Drinks & Co Events",
        location: "Brighton, UK",
        type: "published",
        rate: "£150/day",
        description: "Energetic and reliable bar staff needed for a weekend beach festival. Duties include serving drinks, handling payments, and maintaining bar cleanliness. Personal licence holder preferred. Must be comfortable working outdoors in all weather.",
        status: "paused",
        event_date: "2026-07-10",
        end_date: "2026-07-12",
        start_time: "11:00",
        end_time: "23:00",
        duration_type: "multi-day",
        days: 3,
        contract_type: "freelance",
      },
      {
        recruiter_id: recruiterId,
        title: "Floral Designer",
        company: "Blossom Weddings",
        location: "Bath, UK",
        type: "published",
        rate: "£350/day",
        description: "Talented floral designer needed for a series of summer weddings. You will design and install floral arrangements including centrepieces, arches, and bouquets. Must have a portfolio demonstrating wedding floral work and the ability to work within a budget.",
        status: "closed",
        event_date: "2026-06-01",
        end_date: "2026-08-31",
        start_time: "06:00",
        end_time: "16:00",
        duration_type: "multi-day",
        days: 10,
        contract_type: "freelance",
      },
      {
        recruiter_id: recruiterId,
        title: "Production Assistant",
        company: "TechStage Solutions",
        location: "Manchester, UK",
        type: "published",
        rate: "£180/day",
        description: "Production assistant needed for a live TV broadcast event. You will assist the production manager with logistics, runner duties, and on-site coordination. Great opportunity for someone looking to build experience in live event production.",
        status: "active",
        event_date: "2026-03-22",
        start_time: "06:00",
        end_time: "20:00",
        duration_type: "single-day",
        days: 1,
        contract_type: "freelance",
      },
    ];

    console.log(`🌱 Seeding ${jobs.length} production jobs...`);

    for (const job of jobs) {
      await storage.createJob(job as any);
    }

    console.log("✅ Production jobs seeded successfully");
  } catch (error) {
    console.error("❌ Failed to seed production jobs:", error);
  }
}
