import type { HelpEntry } from "../types";

const entries: HelpEntry[] = [
  {
    key: "dashboard.tab.applications",
    scope: "feature",
    body: "Everyone who has applied to your live jobs, ready to shortlist or hire.",
    audience: ["recruiter", "admin"],
    version: 1,
  },
  {
    key: "dashboard.tab.bookings",
    scope: "feature",
    title: "Bookings",
    body: "Track your confirmed crew across every job, from first enquiry through to completed.",
    audience: ["recruiter", "admin"],
    priority: 8,
    oncePerUser: true,
    minVisits: 2,
    maxVisits: 12,
    version: 1,
  },
  {
    key: "dashboard.tab.crew",
    scope: "feature",
    title: "My Crew",
    body: "Keep your favourite freelancers in one place and rebook them in a click, no searching.",
    audience: ["recruiter", "admin"],
    priority: 7,
    oncePerUser: true,
    minVisits: 2,
    maxVisits: 12,
    version: 1,
  },
  {
    key: "dashboard.crewSearch",
    scope: "feature",
    body: "Search every freelancer on EventLink by skill, role or location, then save the ones you like.",
    audience: ["recruiter", "admin"],
    version: 1,
  },
  {
    key: "dashboard.saveFreelancer",
    scope: "action",
    body: "Save a freelancer to My Crew and you can rebook them in one click, no searching.",
    audience: ["recruiter", "admin"],
    priority: 6,
    oncePerUser: true,
    minVisits: 2,
    maxVisits: 12,
    version: 1,
  },
  {
    key: "action.application.hire",
    scope: "action",
    body: "Confirms this freelancer for the job and closes it to new applicants.",
    audience: ["recruiter", "admin"],
    version: 1,
  },
  {
    key: "action.application.decline",
    scope: "action",
    body: "Lets the applicant know they weren't selected this time.",
    audience: ["recruiter", "admin"],
    version: 1,
  },
  {
    key: "action.application.hide",
    scope: "action",
    body: "Removes this application from your list; the applicant isn't told.",
    audience: ["recruiter", "admin"],
    version: 1,
  },
  {
    key: "action.invitation.accept",
    scope: "action",
    body: "Accept the invitation to apply and move it into your applications.",
    audience: ["freelancer"],
    version: 1,
  },
  {
    key: "action.invitation.decline",
    scope: "action",
    body: "Turn down the invitation; the employer is notified.",
    audience: ["freelancer"],
    version: 1,
  },
  {
    key: "dashboard.tab.myJobs",
    scope: "feature",
    body: "The jobs you have applied to, with their status and any messages.",
    audience: ["freelancer"],
    version: 1,
  },
  {
    key: "dashboard.tab.freelancerApplications",
    scope: "feature",
    body: "The jobs you've applied to, with their status and any messages.",
    audience: ["freelancer"],
    version: 1,
  },
  {
    key: "dashboard.tab.pendingRatings",
    scope: "feature",
    body: "People you've worked with who are waiting for your rating.",
    audience: ["freelancer"],
    version: 1,
  },
  {
    key: "dashboard.tab.freelancerPostedJobs",
    scope: "feature",
    body: "Jobs you've posted yourself, and the people who applied to them.",
    audience: ["freelancer"],
    version: 1,
  },
];

export default entries;
